### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by tom10271** [endel/increase-memory-limit#16]
```
module.js:538
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by endel** [comment]
This library has been deprecated. Please use Node.js v8+ and set `NODE_OPTIONS` environment variable. (https://github.com/endel/increase-memory-limit#deprecation-notice)
